# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cromo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cromo_img', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=20)),
                ('diseño', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('cromo_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='test_project.Cromo')),
                ('nombre', models.CharField(max_length=40)),
                ('f_creacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('cromo_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='test_project.Cromo')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('posicion', models.CharField(max_length=20)),
                ('peso', models.CharField(max_length=20)),
                ('altura', models.CharField(max_length=20)),
                ('club_actual', models.CharField(max_length=40)),
                ('f_nacimiento', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='cromo',
            name='page_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_project.Page'),
        ),
    ]
