# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cromo',
            name='tipo',
            field=models.CharField(choices=[('jr', 'Jugador'), ('es', 'Estadio')], default='jr', max_length=2),
        ),
    ]
