# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0002_cromo_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('page_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='test_project.Page')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Miscaleneo',
            fields=[
                ('page_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='test_project.Page')),
                ('description_text', models.CharField(max_length=300)),
                ('description_misc', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='page',
            name='diseño',
            field=models.CharField(choices=[('PA', 'Pais'), ('MS', 'Miscaleneo')], default='PA', max_length=2),
        ),
    ]
