# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0003_auto_20180401_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='country_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test_project.Country'),
        ),
    ]
