# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 02:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0004_jugador_country_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugador',
            old_name='country_id',
            new_name='seleccion',
        ),
    ]
